language: python
python:
  - "3.8"

env:
  - DB_DSN=postgresql://postgres@localhost:5432/postgres
install:
  - pip install .[dev,e2e,ci]

services:
  - postgresql

script:
  - pytest --cov=pg_stream_copy tests
  - mypy .
  - pyflakes .

deploy:
  provider: pypi
  user: FIXME
  password: FIXME
  on:
    tags: true

after_success:
  - codecov