language: python
python:
  - "3.8"
install:
  - pip install .[dev,test,ci]
services:
  - postgresql
addons:
  postgresql: "12"
env:
  - DB_DSN=postgres

script:
  - pytest --cov=pg_stream_copy tests/unit
  - mypy .
  - pyflakes .

deploy:
  provider: pypi
  user: FIXME
  password: FIXME
  on:
    tags: true

after_success:
  - codecov