language: python
python: 3.6  # to speed up build
dist: bionic

services:
  - docker

branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/  # tags with versions

cache:
  pip: true  # for codecov installation
  directories:
  - .pip_cache  # for docker pip installation

jobs:
  include:
    - stage: test
      env:
        - PG_VERSION=9
        - PYTHON_VERSION=3.8
      script: ./bin/tests.sh
    - stage: test
      env:
        - PG_VERSION=10
        - PYTHON_VERSION=3.8
      script: ./bin/tests.sh
    - stage: test
      env:
        - PG_VERSION=11
        - PYTHON_VERSION=3.8
      script: ./bin/tests.sh
    - stage: test
      env:
        - PG_VERSION=12
        - PYTHON_VERSION=3.7
      script: ./bin/tests.sh
    - stage: test
      env:
        - PG_VERSION=12
        - PYTHON_VERSION=3.8
      install: pip install codecov
      script: ./bin/tests.sh
      after_success:
        - codecov

    - stage: linters
      script: ./bin/linters.sh

    - stage: deploy
      if: tag IS present
      env:
        - TWINE_USERNAME=__token__
        - secure: rP/9tRkRi6sw46ZqWhdXouNpD+LxNa7sQa1O7FepgA59fH2CW0uPfmV4F/JmPiGVujUZJz12U3OR8PFcbNZGa2/0DMVh6X7qIxpiRPlik/v4WRND/f7lZ5XoH0RP+ntkL20rh7LsA1gRrQtLY9gu5yC3LAta1qwAUj2NneIMbsQ1YGZCFGhNEZoR/Tn72kVURTkMbz1a7XmWNE9h3I0Casj9DndWJwLHGv2OqNdVnXj7Go9R3gb8Yodwkt4oMvN5lvB8pFDiUYi3ZZY52ymNcuY7ctwwwHv9UOyNoJSVZzne5mmqT3jwucJfXtcQOEMBwfsbQrUGXVFo9ydUeCL/CFC0D1qRO9/P3zsncIzTHEq4is9bkmPKFEsJfbPk8HP2tbZUIaWRMu32r4lKsjjPC9clWl6SA2/OIMNw3V2Lfecj253QElLDRmLArSYhuQCB0ACLYZ+PyQ6Dt4laV2OJej8a6CP27nhRrWbK0r3jm5+PsKHDx4qMIwHkl9RVg7XmlNA2OX0zWkje01U7BiCsE6req4Mwu/xuy7srpyuRQcPUGuf6HG/croIcH+oT/m+DqbqpTOTu5NgOnoYqkB88AuOmL5HxQiq8HgDw8EJsp1n5h6f2QFLYEg4BxlM9ee85SYmrKotvyvr4qGpdkk+TlwEM7v4uH/zs21cseiWvwGA=
      script: ./bin/deploy.sh
