language: python
python:
  - "3.7"
  - "3.8"
env:
  # - PG_VERSION=10
  - PG_VERSION=11
  - PG_VERSION=12
install:
  - pip install .[dev,e2e,ci]

jobs:
  include:
    - stage: test
      services:
        - postgresql
      addons:
        postgresql: $PG_VERSION
      env:
        - DB_DSN=postgresql://postgres@localhost:5432/e2e_db
      before_install:
        - sudo apt-get update
        - sudo apt-get --yes remove postgresql\*
        - sudo apt-get install -y postgresql-${PG_VERSION} postgresql-client-${PG_VERSION}
        - sudo cp /etc/postgresql/{9.6,$PG_VERSION}/main/pg_hba.conf
        - sudo service postgresql restart $PG_VERSION
      before_script:
        - psql -c 'CREATE DATABASE e2e_db;' -U postgres
      script: pytest --cov=pg_stream_copy tests/
      after_success:
        - codecov
    - stage: mypy
      script: mypy .
    - stage: pyflakes
      script: pyflakes .
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: FIXME
        password: FIXME
        on:
          tags: true