language: python
python:
  - "3.8"
install:
  - pip install .[dev,e2e,ci]
env:
  - DB_DSN=postgresql://postgres@localhost

services:
  - postgresql
addons:
  postgresql: "12"

script:
  - pytest --cov=pg_stream_copy tests
  - mypy .
  - pyflakes .

deploy:
  provider: pypi
  user: FIXME
  password: FIXME
  on:
    tags: true

after_success:
  - codecov