language: python
python:
  - "3.8"
install:
  - pip install .[dev,e2e,ci]
env:
  - DB_DSN=postgresql://postgres@localhost:5432/e2e_db

services:
  - postgresql
addons:
  postgresql: "11"

before_script:
  - psql -c 'CREATE DATABASE e2e_db;' -U postgres

script:
  - pytest --cov=pg_stream_copy tests
  - mypy .
  - pyflakes .

deploy:
  provider: pypi
  user: FIXME
  password: FIXME
  on:
    tags: true

after_success:
  - codecov