version: "3.2"

services:
  db:
    image: postgres:${PG_VERSION:-12}-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  py:
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${UID}"
        PYTHON_VERSION: "${PYTHON_VERSION:-3.8}"
    container_name: pg_stream_copy_py
    environment:
      DB_DSN: postgresql://postgres:postgres@db
    depends_on:
      - db
    volumes:
      - ./:/home/python/code
      - pip_cache:/home/python/.cache/pip

volumes:
  pip_cache: