version: "3.2"

services:
  db:
    image: postgres:${PG_VERSION:-14}-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  py:
    image: rtbhouse-apps/pg-stream-copy:${DOCKER_TAG:-latest}
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${UID}"
        PYTHON_VERSION: "${PYTHON_VERSION:-3.10}"
    container_name: pg_stream_copy_py
    environment:
      DB_DSN: postgresql://postgres:postgres@db
    depends_on:
      - db
    volumes:
      - ./:/home/python/code
