version: "3.7"

services:
  postgres10:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  postgres11:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  postgres12:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  e2e:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    depends_on:
      - postgres10
      - postgres11
      - postgres12
